version: "3.7"

services:
    reverse-proxy:
        image: traefik:v2.0
        container_name: global_traefik
        command: --api.insecure=true --providers.docker
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - default

networks:
    default:
        external:
            name: gateway
